export { default as authAPI } from "./auth";
export { default as carouselAPI } from "./carousel";
export { default as sellingPointsAPI } from "./selling-points";
export * from "./why-visit";
export * from "./attraction";
export * from "./pricing";
export { default as profileAPI } from "./profile";
export { default as contactAPI } from "./contact";
export { default as bookingAPI } from "./booking";
export * from "./gallery";
export * from "./news";
export * from "./regulations";
export { default as uploadAPI } from "./upload";
export { default as destinationsAPI } from "./destinations";
export * from "./facilities";
export * from "./heritage";
export * from "./analytics";
